# Current can't use.......................

language: android

jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-23

android:
  components:
    - build-tools-23.0.1
    - android-23

before_install:
 - chmod +x gradlew

script:
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo "ndk.dir=${ANDROID_NDK_HOME}" >> local.properties
    - ./gradlew assemble
    - ./gradlew check

# Current can't use.