language: android

jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a x86

android:
  components:
    - build-tools-23.0.1
    - android-23

before_install:
 - chmod +x gradlew

script:
    ./gradlew assemble && \
    ./gradlew check
